import type { Metadata, Viewport } from "next";
import {
  APP_URL,
  AUTHOR_NAME,
  TWITTER_HANDLE,
} from "@/lib/site-config";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default: "Samir Shaikh - AI Backend Engineer | Node.js Developer",
    template: "%s | Samir Shaikh",
  },
  description:
    "Samir Shaikh is an AI Backend Engineer building RAG pipelines, LLM-powered chatbots, and scalable Node.js systems, and is exploring Forward Deployed Engineer roles that combine backend depth with direct customer ownership.",
  keywords: [
    "Samir Shaikh",
    "Samir Shaikh Portfolio",
    "AI Backend Engineer",
    "AI Engineer",
    "Forward Deployed Engineer",
    "Applied AI Engineer",
    "Customer-Facing Engineer",
    "Backend Engineer AI",
    "LLM Engineer",
    "RAG Engineer",
    "Retrieval Augmented Generation",
    "Vector Search",
    "Vector Database",
    "pgvector",
    "Semantic Search",
    "Vercel AI SDK",
    "Google Gemini API",
    "OpenAI API",
    "Prompt Engineering",
    "AI Chatbot Development",
    "LLM Integration",
    "Embeddings",
    "Node.js Developer",
    "Backend Developer",
    "Backend Developer India",
    "Node.js Backend Developer",
    "Express.js",
    "NestJS",
    "GraphQL",
    "REST API",
    "Microservices",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Firebase",
    "Drizzle ORM",
    "Sequelize",
    "BullMQ",
    "Apache Kafka",
    "Docker",
    "TypeScript",
    "JavaScript",
    "Full Stack Developer",
    "Next.js",
    "React",
    "Serwist",
    "Sharp",
    "Nodemailer",
    "TipTap",
    "Web Developer",
    "Open to Remote",
    "Logicwind",
    "Uka Tarsadia University",
    "Gujarat Developer",
    "API Integration",
    "JWT Authentication",
    "Socket.io",
    "OpenTelemetry",
    "Prometheus",
    "Grafana",
    "CI/CD",
    "GitHub Actions",
  ],
  authors: [{ name: AUTHOR_NAME, url: APP_URL }],
  creator: AUTHOR_NAME,
  openGraph: {
    title: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer",
    description:
      "Samir Shaikh is an AI Backend Engineer and AI SDE building RAG pipelines, LLM-powered chatbots, agentic AI systems, and scalable Node.js systems. Exploring Forward Deployed Engineer roles with direct customer ownership.",
    url: APP_URL,
    siteName: "Samir Shaikh Portfolio",
    images: [
      {
        url: "/Filled_Logo.png",
        width: 1200,
        height: 630,
        alt: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer",
    description:
      "AI Backend Engineer and AI SDE building RAG pipelines, LLM-powered chatbots, agentic AI systems, and scalable Node.js systems.",
    images: ["/Filled_Logo.png"],
    creator: TWITTER_HANDLE,
  },
  verification: {
    google: "H6Pq0eI_0M2sSwSWyHpuCbS7ufcyBMaw_r2k7VCv9Ok",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: APP_URL,
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
};
