import {
  APP_URL,
  AUTHOR_NAME,
  AUTHOR_EMAIL,
  AUTHOR_PHONE,
} from "@/lib/site-config";

export function getRootJsonLd() {
  return [
    {
      "@context": "https://schema.org",
      "@type": "Person",
      name: AUTHOR_NAME,
      url: APP_URL,
      email: AUTHOR_EMAIL,
      telephone: AUTHOR_PHONE,
      jobTitle: "AI Backend Engineer",
      description:
        "AI Backend Engineer with production experience architecting scalable, event-driven backend solutions and Retrieval-Augmented Generation (RAG) systems, with a strong interest in customer-embedded, forward-deployed engineering work.",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Vapi / Surat",
        addressRegion: "Gujarat",
        addressCountry: "IN",
      },
      sameAs: [
        "https://linkedin.com/in/samir-shaikh-760b932a8",
        "https://github.com/ShaikhSamir786",
      ],
      alumniOf: {
        "@type": "CollegeOrUniversity",
        name: "Uka Tarsadia University",
        sameAs: "https://utu.ac.in",
      },
      knowsAbout: [
        "AI Backend Engineering",
        "Retrieval Augmented Generation (RAG)",
        "LLM Integration",
        "Forward Deployed Engineering",
        "Customer-Embedded Problem Solving",
        "End-to-End Ownership",
        "Vector Search",
        "pgvector",
        "Semantic Search",
        "Embeddings",
        "Vercel AI SDK",
        "Google Gemini API",
        "Prompt Engineering",
        "AI Chatbot Development",
        "Node.js",
        "Express.js",
        "NestJS",
        "GraphQL",
        "REST APIs",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Redis",
        "Firebase",
        "BullMQ",
        "Apache Kafka",
        "Docker",
        "TypeScript",
        "JavaScript",
        "JWT",
        "Socket.io",
        "Sequelize",
        "OpenTelemetry",
        "Prometheus",
        "Grafana",
        "GitHub Actions",
        "CI/CD",
        "Microservices",
        "Next.js",
        "React",
      ],
      worksFor: {
        "@type": "Organization",
        name: "Logicwind",
      },
    },
    {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: "Samir Shaikh Portfolio",
      url: APP_URL,
      description:
        "Portfolio of Samir Shaikh, AI Backend Engineer specializing in RAG pipelines, LLM-powered chatbots, and event-driven microservices.",
      author: {
        "@type": "Person",
        name: AUTHOR_NAME,
      },
    },
  ];
}
